# Name your project
name: 'dbt_dem'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_dem'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:   
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_dem:
    # Config indicated by + and applies to all files under models/example/
    prepared:
      +schema: dbt_prepared
      +materialized: table
    warehouse:
      +schema: dbt_warehouse
      +materialized: table
    marts:
      data_analyst:
        +schema: dbt_mrt_marketing
        +materialized: incremental
        +incremental_strategy: "merge"

      data_analyst:
        +schema: dbt_mrt_analyst
        +materialized: incremental
        +incremental_strategy: "merge"

# # Configuring seeds
# seeds:
#   dbt_dem:  
#       +schema: dbt_staged 
#       delimiter: ","

