dbt_dem:
  outputs:
    dev:
      dataset: dbt_staged
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: service-account
      keyfile: 'auth/perso_yr_dbt_prt.json'
      priority: interactive
      project: data-axe-430306-r6
      threads: 3
      type: bigquery
  target: dev
