version: 2

models:


  - name: mrt_customer_analysis
    description: "Aggregates interaction and loyalty data to provide insights into customer engagement and loyalty point trends."
    columns:
      - name: date_id
        description: "Identifier for the date of customer interactions."
        tests:
          - not_null
      - name: consumer_id
        description: "Identifier for the consumer involved in interactions."
        tests:
          - not_null
      - name: total_interactions
        description: "Total number of interactions with the consumer."
        tests:
          - not_null
      - name: total_points_earned
        description: "Total loyalty points earned by the consumer."
      - name: total_points_redeemed
        description: "Total loyalty points redeemed by the consumer."
      - name: average_points_balance
        description: "Average balance of loyalty points for the consumer."
        tests:
          - not_null

  - name: mrt_inventory_analysis
    description: "Provides insights into stock levels, reorders, and delivery metrics for inventory management."
    columns:
      - name: date_id
        description: "Identifier for the date of inventory record."
        tests:
          - not_null
      - name: item_id
        description: "Identifier for the item in inventory."
        tests:
          - not_null
      - name: total_stock
        description: "Total quantity of item stock on hand."
        tests:
          - not_null
      - name: total_reorders
        description: "Total quantity set for reorders."
        tests:
          - not_null
      - name: total_ordered_quantity
        description: "Total quantity of item ordered."
        tests:
          - not_null
      - name: total_delivered_quantity
        description: "Total quantity of item delivered."
        tests:
          - not_null
  - name: mrt_location_analysis
    description: "Provides geographic distribution and sales insights across different locations."
    columns:
      - name: location_id
        description: "Unique identifier for each location."
        tests:
          - unique
          - not_null
      - name: city
        description: "City where the location is based."
        tests:
          - not_null
      - name: country
        description: "Country where the location is based."
        tests:
          - not_null
      - name: total_sales
        description: "Total sales for each location."
        tests:
          - not_null
      - name: total_transactions
        description: "Total number of transactions that occurred at each location."
        tests:
          - not_null
      - name: average_transaction_value
        description: "Average transaction value per location."

  - name: mrt_product_analysis
    description: "Provides insights into product performance including sales metrics and stock levels."
    columns:
      - name: product_id
        description: "Unique identifier for each product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product."
        tests:
          - not_null
      - name: category
        description: "Category to which the product belongs."
        tests:
          - not_null
      - name: brand
        description: "Brand of the product."
        tests:
          - not_null
      - name: supplier
        description: "Supplier providing the product."
      - name: total_sales
        description: "Total sales generated by the product."
        tests:
          - not_null
      - name: total_quantity_sold
        description: "Total quantity of the product sold."
        tests:
          - not_null
      - name: average_price
        description: "Average selling price of the product."
